inputs:
  version:
    description: "A version to install lambroll"
    default: "v1.0.5"
runs:
  using: "composite"
  steps:
    - name: Set file name
      id: set-filename
      run: |
        case "${{ runner.os }}" in
          Linux) BIN_OS="linux" ;;
          macOS) BIN_OS="darwin" ;;
          *) BIN_OS="linux" ;;
        esac

        case "${{ runner.arch }}" in
          X64) BIN_ARCH="amd64" ;;
          ARM64) BIN_ARCH="arm64" ;;
          *) BIN_ARCH="amd64" ;;
        esac

        FILENAME=lambroll_${{ inputs.version }}_${BIN_OS}_${BIN_ARCH}.tar.gz
        echo "FILENAME=$FILENAME" >> $GITHUB_OUTPUT
      shell: bash
    - run: |
        mkdir -p /tmp/lambroll-${{ inputs.version }}
        cd /tmp/lambroll-${{ inputs.version }}
        curl -sL https://github.com/fujiwara/lambroll/releases/download/${{ inputs.version }}/${{ steps.set-filename.outputs.FILENAME }} | tar zxvf -
        sudo install lambroll /usr/local/bin
      shell: bash
