name: test action
on:
  push:
    branches:
      - v1
      - v1-actions-test
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        env:
          - runner: ubuntu-latest
          - runner: macos-latest
    name: test action
    runs-on: ${{ matrix.env.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: fujiwara/lambroll@${{ github.ref_name }}
        with:
          version: v1.0.5
      - run: |
          lambroll version 2>&1 | fgrep v1.0.5
